# Generated by Django 2.2.13 on 2021-03-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191206_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('Single-AC', 'Single-AC'), ('Double-AC', 'Double-AC'), ('Single-NON-AC', 'Single NON-AC'), ('Double-NON-AC', 'Double-NON-AC'), ('BedSitter', 'BedSitter'), ('One-BedRoom', 'One-BedRoom'), ('Two-BedRoom', 'Two-BedRoom'), ('Three-BedRoom', 'Three-BedRoom')], max_length=20),
        ),
    ]
