# Generated by Django 2.2.13 on 2021-03-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210309_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prereservation',
            name='room_type',
            field=models.CharField(blank=True, choices=[('Single-AC', 'Single-AC'), ('Double-AC', 'Double-AC'), ('Single-NON-AC', 'Single NON-AC'), ('Double-NON-AC', 'Double-NON-AC'), ('BedSitter', 'BedSitter'), ('One-BedRoom', 'One-BedRoom'), ('Two-BedRoom', 'Two-BedRoom'), ('Three-BedRoom', 'Three-BedRoom')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(blank=True, choices=[('Single-AC', 'Single-AC'), ('Double-AC', 'Double-AC'), ('Single-NON-AC', 'Single NON-AC'), ('Double-NON-AC', 'Double-NON-AC'), ('BedSitter', 'BedSitter'), ('One-BedRoom', 'One-BedRoom'), ('Two-BedRoom', 'Two-BedRoom'), ('Three-BedRoom', 'Three-BedRoom')], max_length=20, null=True),
        ),
    ]
